from test1.exceptions.CommonBaseException import CommonBaseException


class AdditionOperationException(CommonBaseException):
    pass
