from test1.exceptions.CommonBaseException import CommonBaseException


class MultiplicationOperationException(CommonBaseException):
    pass
